<table class='datalist'>
	<thead class='datalist-head'>
		<tr class='title-row'>
			<th class='s-index' s-index='_id' style='width: 165px;'>ID</th>
			<th class='s-index' s-index='orgName' style='width: 485px;'>组织名</th>
			<th></th>
		</tr>
		<tr class='search-row'>
			<th></th>
			<th><input class='q-index' q-index='orgName' type='text' name='' value='' /></th>
			<th><div class='query-invoker' class='button'>Search</div></th>
		</tr>
	</thead>
	<tbody class='datalist-body'>
	</tbody>
	<tfoot class='datalist-foot'>
		<tr><td id='datalist-paginator' colspan='3'>
		</td></tr>
	</tfoot>
</table>

<script>
	window.restUrl = '/adminrest/adminrest-org.json'
</script>

<script type='text/template' id='data-row'>
<td>
	{{data.id}}
</td>
<td>
	{{data.orgName}}
</td>
<td>
	<a href='/admin/admin-org/edit/id/{{data.id}}'>编辑</a>
	<a href='/admin/admin-user/index/orgCode/{{data.id}}'>账户管理</a>
	<a href='/admin/admin-site/index/orgCode/{{data.id}}'>网站管理</a>
</td>
</script>


<script data-main="<?php echo $this->envConfig('extUrl')?>/app/data" src="<?php echo $this->envConfig('extUrl')?>/require-jquery.js"></script>
