<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AccountDocumentSiteHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['organizationCode'])) {
            $value = $data['organizationCode'];
            $return = (string) $value;
            $this->class->reflFields['organizationCode']->setValue($document, $return);
            $hydratedData['organizationCode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['remoteSiteId'])) {
            $value = $data['remoteSiteId'];
            $return = (string) $value;
            $this->class->reflFields['remoteSiteId']->setValue($document, $return);
            $hydratedData['remoteSiteId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['globalSiteId'])) {
            $value = $data['globalSiteId'];
            $return = (string) $value;
            $this->class->reflFields['globalSiteId']->setValue($document, $return);
            $hydratedData['globalSiteId'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['domains']) ? $data['domains'] : null;
        $return = new \Doctrine\ODM\MongoDB\PersistentCollection(new \Doctrine\Common\Collections\ArrayCollection(), $this->dm, $this->unitOfWork, '$');
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['domains']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['domains']->setValue($document, $return);
        $hydratedData['domains'] = $return;

        /** @Field(type="boolean") */
        if (isset($data['active'])) {
            $value = $data['active'];
            $return = (bool) $value;
            $this->class->reflFields['active']->setValue($document, $return);
            $hydratedData['active'] = $return;
        }
        return $hydratedData;
    }
}